apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>APP 1</title>
    </head>
    <body>
      <h1>Hello from APP 1</h1>
    </body>
    </html>