Vagrant.configure("2") do |config|
    # Base Ubuntu image (latest LTS)
    config.vm.box = "ubuntu/jammy64"
    # Common settings for both machines
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    # Server (Controller Node)
    config.vm.define "hfanzaouS" do |server|
        server.vm.hostname = "hfanzaouS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.synced_folder "./confs", "/configs"
        server.vm.provision "shell", path: "./scripts/server.sh"
    end
end    
