Vagrant.configure("2") do |config|
    # Base Ubuntu image (latest LTS)
    config.vm.box = "ubuntu/jammy64"
    config.vm.boot_timeout = 600  
    # Common settings for both machines
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" # 512MB might be too low for K3s
      vb.cpus = 1
    end

    # Server (Controller Node)
    config.vm.define "hfanzaouS" do |server|
        server.vm.hostname = "hfanzaouS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.synced_folder "./configs", "/apps"
        server.vm.provision "shell", path: "./server.sh"
    end
end    
