Vagrant.configure("2") do |config|
    # Base Ubuntu image (latest LTS)
    config.vm.box = "bento/debian-12"
    config.vm.boot_timeout = 600  
    # Common settings for both machines
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" # 512MB might be too low for K3s
      vb.cpus = 1
    
    end

    # Server (Controller Node)
    config.vm.define "hfanzaouS" do |server|
        server.vm.hostname = "hfanzaouS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provision "shell", path: "./server.sh"
    end

    # ServerWorker (Agent Node)
    config.vm.define "hfanzaouSW" do |worker|
        worker.vm.hostname = "hfanzaouSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provision "shell", path: "./worker.sh"
    end
end    
