apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>APP 2</title>
    </head>
    <body>
      <h1>Hello from APP 2</h1>
    </body>
    </html>