apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebensalt-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebensalt-playground
  template:
    metadata:
      labels:
        app: ebensalt-playground
    spec:
      containers:
        - name: playground
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
