apiVersion: v1
kind: Service
metadata:
  name: ebensalt-playground
  namespace: dev
spec:
  selector:
    app: ebensalt-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
